server:
  port: 8091

spring:
  application:
    name: order-app
  redis:
    database: 2
    host: 192.168.3.150
    port: 6379
rabbitmq:
  host: 192.168.99.100
  port: 5672
  username: admin
  password: admin
  virtualHost: /
  cacheSize: 10